apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-predictor
  namespace: deal-hunter
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      storageUri: pvc://model-store/granite-3.2-8b-instruct
    minReplicas: 1
    maxReplicas: 1
